<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class GuruSeeder extends Seeder
{
    public function run(): void
    {
        $guru = [
            [
                'kode_guru' => 'GR-00011001', // TMT: 2000-01-10, urutan 01
                'nama' => 'Ahmad Fauzi',
                'foto' => null,
                'nuptk' => '1234567890123456',
                'jk' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1975-05-15',
                'nik' => '3201011505750001',
                'nip' => '197505152000121001',
                'status_kepegawaian' => 'PNS',
                'jenis_ptk' => 'Guru Mapel',
                'gelar_depan' => 'Drs.',
                'gelar_belakang' => 'M.Pd',
                'jenjang' => 'S2',
                'prodi' => 'Pendidikan Matematika',
                'sertifikasi' => 'Ya',
                'tmt_kerja' => '2000-01-10',
                'tugas_tambahan' => 'Kepala Sekolah',
                'mengajar' => 'Matematika',
                'jam_tugas_tambahan' => 18,
                'jjm' => 6,
                'total_jjm' => 24,
                'kompetensi' => null,
            ],
            [
                'kode_guru' => 'GR-05011001', // TMT: 2005-01-10, urutan 01
                'nama' => 'Budi Santoso',
                'foto' => null,
                'nuptk' => null,
                'jk' => 'L',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1980-03-12',
                'nik' => null,
                'nip' => null,
                'status_kepegawaian' => 'PNS',
                'jenis_ptk' => 'Guru Mapel',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.Pd',
                'jenjang' => 'S1',
                'prodi' => 'Pendidikan Bahasa Indonesia',
                'sertifikasi' => null,
                'tmt_kerja' => '2005-01-10',
                'tugas_tambahan' => null,
                'mengajar' => 'Bahasa Indonesia',
                'jam_tugas_tambahan' => null,
                'jjm' => 24,
                'total_jjm' => 24,
                'kompetensi' => null,
            ],
            [
                'kode_guru' => 'GR-08080101', // TMT: 2008-08-01, urutan 01
                'nama' => 'Eko Prasetyo',
                'foto' => null,
                'nuptk' => null,
                'jk' => 'L',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1983-07-22',
                'nik' => null,
                'nip' => null,
                'status_kepegawaian' => 'GTY',
                'jenis_ptk' => 'Guru Mapel',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.T',
                'jenjang' => 'S1',
                'prodi' => 'Teknik Komputer',
                'sertifikasi' => null,
                'tmt_kerja' => '2008-08-01',
                'tugas_tambahan' => null,
                'mengajar' => 'Teknik Otomotif',
                'jam_tugas_tambahan' => null,
                'jjm' => 24,
                'total_jjm' => 24,
                'kompetensi' => null,
            ],
            [
                'kode_guru' => 'GR-10070101', // TMT: 2010-07-01, urutan 01
                'nama' => 'Siti Nurhaliza',
                'foto' => null,
                'nuptk' => null,
                'jk' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1985-08-20',
                'nik' => null,
                'nip' => null,
                'status_kepegawaian' => 'GTY',
                'jenis_ptk' => 'Guru Mapel',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.Pd',
                'jenjang' => 'S1',
                'prodi' => 'Pendidikan Administrasi Perkantoran',
                'sertifikasi' => null,
                'tmt_kerja' => '2010-07-01',
                'tugas_tambahan' => null,
                'mengajar' => 'Administrasi Perkantoran',
                'jam_tugas_tambahan' => null,
                'jjm' => 24,
                'total_jjm' => 24,
                'kompetensi' => null,
            ],
            [
                'kode_guru' => 'GR-10070102', // TMT: 2010-07-01, urutan 02 (tanggal sama)
                'nama' => 'Dewi Lestari',
                'foto' => null,
                'nuptk' => null,
                'jk' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1988-11-05',
                'nik' => null,
                'nip' => null,
                'status_kepegawaian' => 'GTY',
                'jenis_ptk' => 'Guru Mapel',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.Pd',
                'jenjang' => 'S1',
                'prodi' => 'Pendidikan Bahasa Inggris',
                'sertifikasi' => null,
                'tmt_kerja' => '2010-07-01',
                'tugas_tambahan' => null,
                'mengajar' => 'Bahasa Inggris',
                'jam_tugas_tambahan' => null,
                'jjm' => 24,
                'total_jjm' => 24,
                'kompetensi' => null,
            ],
            // Staff Kurikulum
            [
                'kode_guru' => 'GR-12070101', // TMT: 2012-07-01, urutan 01
                'nama' => 'Rina Wulandari',
                'foto' => null,
                'nuptk' => null,
                'jk' => 'P',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1987-04-15',
                'nik' => null,
                'nip' => null,
                'status_kepegawaian' => 'GTY',
                'jenis_ptk' => 'Tenaga Administrasi Sekolah',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.Pd',
                'jenjang' => 'S1',
                'prodi' => 'Pendidikan',
                'sertifikasi' => null,
                'tmt_kerja' => '2012-07-01',
                'tugas_tambahan' => 'Kurikulum',
                'mengajar' => null,
                'jam_tugas_tambahan' => 24,
                'jjm' => 0,
                'total_jjm' => 24,
                'kompetensi' => null,
            ],
            // Staff Kesiswaan
            [
                'kode_guru' => 'GR-13070101', // TMT: 2013-07-01, urutan 01
                'nama' => 'Agus Setiawan',
                'foto' => null,
                'nuptk' => null,
                'jk' => 'L',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1989-06-20',
                'nik' => null,
                'nip' => null,
                'status_kepegawaian' => 'GTY',
                'jenis_ptk' => 'Tenaga Administrasi Sekolah',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.Pd',
                'jenjang' => 'S1',
                'prodi' => 'Pendidikan',
                'sertifikasi' => null,
                'tmt_kerja' => '2013-07-01',
                'tugas_tambahan' => 'Kesiswaan',
                'mengajar' => null,
                'jam_tugas_tambahan' => 24,
                'jjm' => 0,
                'total_jjm' => 24,
                'kompetensi' => null,
            ],
            // Staff Tata Usaha
            [
                'kode_guru' => 'GR-14070101', // TMT: 2014-07-01, urutan 01
                'nama' => 'Lina Handayani',
                'foto' => null,
                'nuptk' => null,
                'jk' => 'P',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1990-08-10',
                'nik' => null,
                'nip' => null,
                'status_kepegawaian' => 'GTY',
                'jenis_ptk' => 'Tenaga Administrasi Sekolah',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.E',
                'jenjang' => 'S1',
                'prodi' => 'Ekonomi',
                'sertifikasi' => null,
                'tmt_kerja' => '2014-07-01',
                'tugas_tambahan' => 'Tata Usaha',
                'mengajar' => null,
                'jam_tugas_tambahan' => 24,
                'jjm' => 0,
                'total_jjm' => 24,
                'kompetensi' => null,
            ],
            [
                'kode_guru' => 'GR-00000000', 
                'nama' => 'Administrator',
                'foto' => null,
                'nuptk' => null,
                'jk' => 'L',
                'tempat_lahir' => '-',
                'tanggal_lahir' => '2000-01-01',
                'nik' => null,
                'nip' => null,
                'status_kepegawaian' => 'Tetap',
                'jenis_ptk' => 'Tenaga Administrasi Sekolah',
                'gelar_depan' => null,
                'gelar_belakang' => null,
                'jenjang' => 'S1',
                'prodi' => 'Teknologi Informasi',
                'sertifikasi' => null,
                'tmt_kerja' => '2000-01-01',
                'tugas_tambahan' => 'Admin',
                'mengajar' => null,
                'jam_tugas_tambahan' => 0,
                'jjm' => 0,
                'total_jjm' => 0,
                'kompetensi' => null,
            ],
        ];

        DB::table('guru')->insert($guru);
    }
}
